spring.application.name=booking


server.port=8082


#spring.datasource.url=jdbc:oracle:thin:@localhost:1521/XEPDB1
#spring.datasource.username=workspace
#spring.datasource.password=wksp#2026
#spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
#spring.jpa.properties.hibernate.default_schema=WORKSPACE

# Spring DataSource Configuration
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# JDBC URL pointing to TNS Alias and Wallet Location
spring.datasource.url=jdbc:oracle:thin:@apexdb_medium?TNS_ADMIN=E:/db-cloud/Wallet_APEXDB


# Database Credentials
spring.datasource.username=ws_project
spring.datasource.password=Shjmun@11223344@

# HikariCP Connection Pool & Oracle Wallet Connection Properties
spring.datasource.hikari.data-source-properties.oracle.net.tns_admin=E:/db-cloud/Wallet_APEXDB
spring.datasource.hikari.data-source-properties.oracle.net.wallet_location=E:/db-cloud/Wallet_APEXDB


# JWT Configuration
jwt.secret=MySuperSecretKeyThatIsVeryLongAndSecure123456789
jwt.expiration=86400000

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=minayousry235@gmail.com
spring.mail.password=shph wwpq wbjl tpvu
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
app.mail.noreply=Misa7a (Do Not Reply) <noreply@misa7a.com>


# Ensure these aren't set to false
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

# Multipart Size
spring.servlet.multipart.max-file-size=4MB
spring.servlet.multipart.max-request-size=4MB

# Server:IP
server.ip=http://localhost:8082/

#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
#logging.level.org.hibernate.orm.jdbc.bind=TRACE